language: php
services:
  - sqllite

php:
  - 5.6

before_script:
  - mysql -u root -e 'create database symfony;'
  - composer self-update
  - composer install

script:
  - ./bin/phpunit --coverage-clover coverage.clover -c app

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover