<?php

namespace AppBundle\Repository;

/**
 * DishInOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DishInOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
