<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DishInCartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DishInCartRepository extends EntityRepository
{

}