<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DishCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DishCategoryRepository extends EntityRepository
{
    public function getCategoriesDishes()
    {
        return $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.dishes != NULL')
            ->getQuery()
            ->getResult();
    }
}
