<?php

namespace AppBundle\Repository;

/**
 * StaticPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaticPageRepository extends \Doctrine\ORM\EntityRepository
{
}
