<?php

namespace AppBundle\Repository;

/**
 * SurveyResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyResultRepository extends \Doctrine\ORM\EntityRepository
{
}
