<?php

namespace AppBundle\Repository;

/**
 * SurveyQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
